name: Backport

on:
  pull_request:
    types: [opened, reopened, edited]

env:
  GH_AUTH: ${{ secrets.GH_AUTH }}

jobs:
  backport:
    name: Check and update backport label of PR

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: pip
          cache-dependency-path: "*requirements.txt"
      - name: Install Dependencies
        run: python3 -m pip install coverage -U pip -r dev-requirements.txt
      - name: Run code
        run: python3 -m bedevere.backport
