name: Close PR

on:
  pull_request:
    types: [opened, synchronize]

env:
  GH_AUTH: ${{ secrets.GH_AUTH }}

jobs:
  close_pr:
    name: close invalid PR

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: pip
          cache-dependency-path: "*requirements.txt"
      - name: Install Dependencies
        run: python3 -m pip install coverage -U pip -r dev-requirements.txt
      - name: Run close_pr.py file
        run: python3 -m bedevere.close_pr
