

name: filepaths

on:
  pull_request:
    types: [opened, reopened, edited]

env:
  GH_AUTH: ${{ secrets.GH_AUTH }}

jobs:
  filepaths:
    name: Checks filepaths on a PR

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/setup-python@v2
        if: "!endsWith(matrix.python-version, '-dev')"
        with:
          python-version: ${{ matrix.python-version }}
      - uses: deadsnakes/action@v2.1.1
        if: endsWith(matrix.python-version, '-dev')
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: python3 -m pip install coverage -U pip -r dev-requirements.txt
      - name: Run code
        run: python3 -m bedevere.filepaths
      
  