name: Review PR

on:
  pull_request:
    types: [review_requested]

env:
  GH_AUTH: ${{ secrets.GH_AUTH }}

jobs:
  review_invalid_pr:
    name: Dismiss review request from the invalid PR

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: pip
          cache-dependency-path: "*requirements.txt"
      - name: Install Dependencies
        run: python3 -m pip install coverage -U pip -r dev-requirements.txt
      - name: Run review_pr.py file
        run: python3 -m bedevere.review_pr
